name: Acceptance Tests
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  acceptance:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [1.16]
        fix-version:
          - fix40
          - fix41
          - fix42
          - fix43
          - fix44
          - fix50
          - fix50sp1
          - fix50sp2
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Check out source
        uses: actions/checkout@v2
      - name: Run Mongo
        run: docker run -d -p 27017:27017 mongo
      - name: Test
        env:
          MONGODB_TEST_CXN: "localhost"
          FIX_TEST: ${{ matrix.fix-version }}
        run: make build-acceptance-server; make $FIX_TEST;