name: Test & Coverage

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        go-version: [ ~1.16 ]
        os: [ ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Cache Go modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Dependencies
        run: go mod tidy
      - name: Run Mongo
        run: docker run -d -p 27017:27017 mongo
      - name: Test
        env:
          MONGODB_TEST_CXN: "localhost"
        run: make ci-test
      - name: Upload coverage
        uses: codecov/codecov-action@v1
        if: matrix.os == 'ubuntu-latest'
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.txt